pub(crate) mod agents;
pub(crate) mod counters;
pub(crate) mod event_log;
pub(crate) mod header;
pub(crate) mod layout;
pub(crate) mod main_panels;
pub(crate) mod metrics;
pub(crate) mod node_detail;
pub(crate) mod nodes;
mod primitives;
pub(crate) mod trends;
